#!/usr/bin/env python3
"""compile-tokens.py — DTCG design tokens -> CSS custom properties + Tailwind theme.

Usage:
  python3 compile-tokens.py tokens.json \
      [--out-css tokens.css] [--out-tailwind theme.css] [--check-only]

- Resolves {primitive...} references from the semantic layer (one level).
- Emits :root { ... } for the light theme: semantic tokens (color group maps
  to bare names --ink/--canvas per token-pipeline.md; other groups keep their
  prefix --font-body/--measure-body) AND primitives (--color-gray-500,
  --font-scale-step3, --space-4).
- If semantic.dark.* exists, emits [data-theme="dark"] overrides.
- Emits a "contrast-pairs:" header consumed by check-contrast.py.
- --check-only: validate without writing files.

Exit 0 = ok, 1 = errors (unresolved refs, bad $value shapes, missing pairs,
ban-listed first-position fonts). Stdlib only.
"""
import argparse, json, re, sys

REF_RE = re.compile(r"^\{(.+)\}$")

def kebab(s):
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s).replace("_", "-").lower()

def flatten(node, path, out, problems):
    if isinstance(node, dict):
        if "$value" in node:
            out[".".join(path)] = node["$value"]
            return
        for k, v in node.items():
            if k.startswith("$") or k == "comment":
                continue  # DTCG $-props and comment fields are annotations, not tokens
            flatten(v, path + [k], out, problems)
    else:
        problems.append(f"non-token leaf at {'.'.join(path)} (missing $value?)")

def resolve(value, flat, where, problems):
    if isinstance(value, str):
        m = REF_RE.match(value.strip())
        if m:
            ref = m.group(1)
            if ref not in flat:
                problems.append(f"unresolved reference {{{ref}}} at {where}")
                return value
            return resolve(flat[ref], flat, where, problems)
        return value
    if isinstance(value, list):  # fontFamily arrays
        return ", ".join(str(v) if " " not in str(v) else f'"{v}"' for v in value)
    return value

def to_css_value(path, value):
    if isinstance(value, (int, float)):
        return str(value)
    return str(value)

CONTRAST_PAIRS = [
    ("ink", "canvas"),
    ("inkMuted", "canvas"),
    ("actionPrimaryText", "actionPrimary"),
    ("inkOnDark", "surfaceDark"),
]

def css_name_for(key):
    """Semantic key -> CSS var name. The color group maps to bare names
    (--ink, --action-primary) per token-pipeline.md; other groups keep
    their prefix (--font-body, --measure-body)."""
    parts = key.split(".")
    if parts[0] == "color":
        parts = parts[1:]
    return "--" + "-".join(kebab(p) for p in parts)

def emit_css(semantic, dark, primitives, flat, problems):
    lines = []
    lines.append("/* GENERATED by compile-tokens.py — do not edit by hand. */")
    pair_hdr = ", ".join(f"{a}/{b}" for a, b in CONTRAST_PAIRS)
    lines.append(f"/* contrast-pairs: {pair_hdr} */")
    lines.append(":root {")
    resolved = {}
    for key, val in sorted(semantic.items()):
        rv = resolve(val, flat, f"semantic.{key}", problems)
        lines.append(f"  {css_name_for(key)}: {to_css_value(key, rv)};")
        resolved[key] = rv
    for key, val in sorted(primitives.items()):
        rv = resolve(val, flat, f"primitive.{key}", problems)
        lines.append(f"  --{kebab(key.replace('.', '-'))}: {to_css_value(key, rv)};")
    lines.append("}")
    if dark:
        lines.append("")
        lines.append('[data-theme="dark"] {')
        for key, val in sorted(dark.items()):
            rv = resolve(val, flat, f"semantic.dark.{key}", problems)
            lines.append(f"  {css_name_for(key)}: {to_css_value(key, rv)};")
        lines.append("}")
    return "\n".join(lines) + "\n", resolved

def emit_tailwind(semantic, flat, problems):
    lines = []
    lines.append("/* GENERATED by compile-tokens.py — Tailwind theme bridge. */")
    lines.append("@theme {")
    for key in sorted(semantic.keys()):
        group = key.split(".")[0]
        tw_prefix = {"color": "--color", "font": "--font", "measure": "--spacing"}.get(group)
        if tw_prefix is None:
            tw_prefix = f"--{kebab(group)}"
        name = "-".join(kebab(p) for p in key.split(".")[1:]) or kebab(group)
        lines.append(f"  {tw_prefix}-{name}: var({css_name_for(key)});")
    lines.append("}")
    return "\n".join(lines) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tokens", nargs="?", default="tokens.json")
    ap.add_argument("--out-css", default="tokens.css")
    ap.add_argument("--out-tailwind", default="tokens.theme.css")
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()

    problems = []
    try:
        with open(args.tokens, encoding="utf-8") as f:
            doc = json.load(f)
    except FileNotFoundError:
        print(f"FAIL: tokens file not found: {args.tokens}")
        return 1
    except json.JSONDecodeError as e:
        print(f"FAIL: JSON parse error: {e}")
        return 1

    flat = {}
    flatten(doc, [], flat, problems)

    semantic = {k[len("semantic."):]: v for k, v in flat.items()
                if k.startswith("semantic.") and not k.startswith("semantic.dark.")}
    dark = {k[len("semantic.dark."):]: v for k, v in flat.items() if k.startswith("semantic.dark.")}
    primitives = {k[len("primitive."):]: v for k, v in flat.items() if k.startswith("primitive.")}

    # Verify the contrast pairs exist in the semantic layer (D3 depends on them)
    for a, b in CONTRAST_PAIRS:
        for need in (f"color.{a}", f"color.{b}"):
            if need not in semantic:
                problems.append(f"semantic.{need} missing — required contrast pair {a}/{b}")

    css, resolved = emit_css(semantic, dark, primitives, flat, problems)
    tw = emit_tailwind(semantic, flat, problems)

    # Ban-list guard at the token level: first-position banned fonts
    for k, v in flat.items():
        if "family" not in k:
            continue
        rv = resolve(v, flat, k, problems)
        first = str(rv).split(",")[0].strip().strip('"').replace(" ", "").lower()
        if first in {"inter", "roboto", "arial", "spacegrotesk", "space-grotesk"}:
            problems.append(f"{k}: banned font '{first}' in first position")

    for p in problems:
        print(f"FAIL: {p}")
    if problems:
        print(f"\n{len(problems)} token problem(s)")
        return 1

    if args.check_only:
        print(f"OK: tokens valid ({len(semantic)} semantic, {len(primitives)} primitive, "
              f"dark={'yes' if dark else 'no'})")
        return 0

    with open(args.out_css, "w", encoding="utf-8") as f:
        f.write(css)
    with open(args.out_tailwind, "w", encoding="utf-8") as f:
        f.write(tw)
    print(f"OK: wrote {args.out_css} and {args.out_tailwind} "
          f"({len(semantic)} semantic + {len(primitives)} primitive tokens, "
          f"dark={'yes' if dark else 'no'})")
    return 0

if __name__ == "__main__":
    sys.exit(main())
