#!/usr/bin/env python3
"""compile-tokens.py — DTCG design tokens -> CSS custom properties + Tailwind theme.

Usage:
  python3 compile-tokens.py tokens.json \
      [--out-css tokens.css] [--out-tailwind theme.css] [--check-only]

- Resolves {primitive...} references from the semantic layer (one level).
- Emits :root { ... } for the light theme: semantic tokens (color group maps
  to bare names --ink/--canvas per token-pipeline.md; other groups keep their
  prefix --font-body/--measure-body) AND primitives (--color-gray-500,
  --font-scale-step3, --space-4).
- If semantic.dark.* exists, emits [data-theme="dark"] overrides.
- Emits a "contrast-pairs:" header consumed by check-contrast.py.
- --check-only: validate without writing files.
- --verify: D.41 — compare what WOULD be emitted with the files on disk, and
  fail on any difference. A compiled theme that outlived its source is the
  same family of defect as a drifted contrast pair: the build artefact keeps
  claiming something the declaration no longer says. Found for real in v7.2 —
  the flagship skins' committed tokens.css still carried a four-pair header
  after the skins had declared seven.

Exit 0 = ok, 1 = errors (unresolved refs, bad $value shapes, missing pairs,
ban-listed first-position fonts, stale compiled output). Stdlib only.
"""
import argparse, json, re, sys

REF_RE = re.compile(r"^\{(.+)\}$")

def kebab(s):
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s).replace("_", "-").lower()

def flatten(node, path, out, problems):
    if isinstance(node, dict):
        if "$value" in node:
            out[".".join(path)] = node["$value"]
            return
        for k, v in node.items():
            if k.startswith("$") or k == "comment":
                continue  # DTCG $-props and comment fields are annotations, not tokens
            flatten(v, path + [k], out, problems)
    else:
        problems.append(f"non-token leaf at {'.'.join(path)} (missing $value?)")

def resolve(value, flat, where, problems):
    if isinstance(value, str):
        m = REF_RE.match(value.strip())
        if m:
            ref = m.group(1)
            if ref not in flat:
                problems.append(f"unresolved reference {{{ref}}} at {where}")
                return value
            return resolve(flat[ref], flat, where, problems)
        return value
    if isinstance(value, list):  # fontFamily arrays
        return ", ".join(str(v) if " " not in str(v) else f'"{v}"' for v in value)
    return value

def to_css_value(path, value):
    if isinstance(value, (int, float)):
        return str(value)
    return str(value)

def css_name_for(key):
    """Semantic key -> CSS var name. The color group maps to bare names
    (--ink, --action-primary) per token-pipeline.md; other groups keep
    their prefix (--font-body, --measure-body)."""
    parts = key.split(".")
    if parts[0] == "color":
        parts = parts[1:]
    return "--" + "-".join(kebab(p) for p in parts)

def var_name(full_key):
    """Fully-qualified token path -> the CSS variable this file emits for it.

    `semantic.color.ink` -> `--ink`, `primitive.radius.md` -> `--radius-md`,
    `component.button.primaryBg` -> `--button-primary-bg`. The dark layer
    reuses its light twin's name, since it is emitted into a different scope
    rather than under a different variable.

    Exists so that a check outside this file (D.39) can ask "what is this token
    called in CSS?" without restating the three rules below — two copies of a
    naming map drift the day one of them is corrected [A.10]."""
    if full_key.startswith("semantic.dark."):
        return css_name_for(full_key[len("semantic.dark."):])
    if full_key.startswith("semantic."):
        return css_name_for(full_key[len("semantic."):])
    for layer in ("primitive.", "component."):
        if full_key.startswith(layer):
            return "--" + kebab(full_key[len(layer):].replace(".", "-"))
    return "--" + kebab(full_key.replace(".", "-"))

def emit_css(semantic, dark, primitives, components, flat, problems, contrast_pairs):
    lines = []
    lines.append("/* GENERATED by compile-tokens.py — do not edit by hand. */")
    pair_hdr = ", ".join(f"{a}/{b}" for a, b in contrast_pairs)
    lines.append(f"/* contrast-pairs: {pair_hdr} */")
    lines.append(":root {")
    resolved = {}
    for key, val in sorted(semantic.items()):
        rv = resolve(val, flat, f"semantic.{key}", problems)
        lines.append(f"  {var_name('semantic.' + key)}: {to_css_value(key, rv)};")
        resolved[key] = rv
    for key, val in sorted(primitives.items()):
        rv = resolve(val, flat, f"primitive.{key}", problems)
        lines.append(f"  {var_name('primitive.' + key)}: {to_css_value(key, rv)};")
    for key, val in sorted(components.items()):
        rv = resolve(val, flat, f"component.{key}", problems)
        lines.append(f"  {var_name('component.' + key)}: {to_css_value(key, rv)};")
    lines.append("}")
    if dark:
        lines.append("")
        lines.append('[data-theme="dark"] {')
        for key, val in sorted(dark.items()):
            rv = resolve(val, flat, f"semantic.dark.{key}", problems)
            lines.append(f"  {var_name('semantic.dark.' + key)}: {to_css_value(key, rv)};")
        lines.append("}")
    return "\n".join(lines) + "\n", resolved

def emit_tailwind(semantic, components, flat, problems):
    lines = []
    lines.append("/* GENERATED by compile-tokens.py — Tailwind theme bridge. */")
    lines.append("@theme {")
    for key in sorted(semantic.keys()):
        group = key.split(".")[0]
        tw_prefix = {"color": "--color", "font": "--font", "measure": "--spacing"}.get(group)
        if tw_prefix is None:
            tw_prefix = f"--{kebab(group)}"
        name = "-".join(kebab(p) for p in key.split(".")[1:]) or kebab(group)
        lines.append(f"  {tw_prefix}-{name}: var({css_name_for(key)});")
    for key in sorted(components.keys()):
        name = "-".join(kebab(p) for p in key.split("."))
        lines.append(f"  --component-{name}: var(--{kebab(key.replace('.', '-'))});")
    lines.append("}")
    return "\n".join(lines) + "\n"

def first_difference(have, want):
    """Point at the first line that moved, so the fix is one look away rather
    than a whole-file diff the reader has to bisect."""
    a, b = have.splitlines(), want.splitlines()
    for i in range(max(len(a), len(b))):
        line_a = a[i] if i < len(a) else "<end of file>"
        line_b = b[i] if i < len(b) else "<end of file>"
        if line_a != line_b:
            return (f"stale from line {i + 1} — on disk {line_a.strip()!r}, "
                    f"from tokens {line_b.strip()!r}")
    return "differs in trailing whitespace"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tokens", nargs="?", default="tokens.json")
    ap.add_argument("--out-css", default=None)
    ap.add_argument("--out-tailwind", default=None)
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--verify", action="store_true",
                    help="D.41: fail if the files on disk differ from what "
                         "this run would write")
    args = ap.parse_args()

    # --verify against the DEFAULT paths compares the tokens with whatever
    # happens to sit in the working directory, and reports "missing" when
    # nothing does. That reads exactly like real staleness and is not — it cost
    # a reviewer a diff hunt on the day D.41 shipped. The floor always passes
    # explicit paths, so requiring them costs nothing and removes the false
    # alarm entirely.
    if args.verify and not (args.out_css and args.out_tailwind):
        print("FAIL: --verify needs explicit --out-css and --out-tailwind. "
              "Comparing against the defaults would measure the working "
              "directory, not the theme that belongs to these tokens.")
        return 2
    args.out_css = args.out_css or "tokens.css"
    args.out_tailwind = args.out_tailwind or "tokens.theme.css"

    problems = []
    try:
        with open(args.tokens, encoding="utf-8") as f:
            doc = json.load(f)
    except FileNotFoundError:
        print(f"FAIL: tokens file not found: {args.tokens}")
        return 1
    except json.JSONDecodeError as e:
        print(f"FAIL: JSON parse error: {e}")
        return 1

    # [Ход 8] Geometry of contrast pairs: declared in data, not hardcoded in code.
    meta_pairs = doc.get("$meta", {}).get("contrastPairs", [])
    contrast_pairs = []
    seen_in_pairs = set()
    for p in meta_pairs:
        fg = p.get("foreground"); bg = p.get("background")
        if not fg or not bg:
            problems.append(f"$meta.contrastPairs entry missing foreground/background: {p}")
            continue
        contrast_pairs.append((fg, bg))
        seen_in_pairs.add(fg); seen_in_pairs.add(bg)

    flat = {}
    flatten(doc, [], flat, problems)

    semantic = {k[len("semantic."):]: v for k, v in flat.items()
                if k.startswith("semantic.") and not k.startswith("semantic.dark.")}
    dark = {k[len("semantic.dark."):]: v for k, v in flat.items() if k.startswith("semantic.dark.")}
    primitives = {k[len("primitive."):]: v for k, v in flat.items() if k.startswith("primitive.")}
    components = {k[len("component."):]: v for k, v in flat.items() if k.startswith("component.")}

    # Layer architecture [A.21]: primitive -> semantic -> component, never back.
    # component refs must target semantic.*; semantic refs must target
    # primitive.* or semantic.* (aliases); primitive refs must stay primitive.
    for key, val in flat.items():
        if not isinstance(val, str):
            continue
        m = REF_RE.match(val.strip())
        if not m:
            continue
        ref = m.group(1)
        if key.startswith("component.") and not ref.startswith("semantic."):
            problems.append(f"{key}: component token must reference semantic.* "
                            f"(got {{{ref}}}) [A.21]")
        elif key.startswith("semantic.") and not (
                ref.startswith("primitive.") or ref.startswith("semantic.")):
            problems.append(f"{key}: semantic token must reference primitive.* "
                            f"or semantic.* (got {{{ref}}}) [A.21]")
        elif key.startswith("primitive.") and not ref.startswith("primitive."):
            problems.append(f"{key}: primitive token must reference primitive.* "
                            f"(got {{{ref}}}) [A.21]")

    # Verify the contrast pairs exist in the semantic layer (D3 depends on them)
    for a, b in contrast_pairs:
        for need in (f"color.{a}", f"color.{b}"):
            if need not in semantic:
                problems.append(f"semantic.{need} missing — required contrast pair {a}/{b}")

    css, resolved = emit_css(semantic, dark, primitives, components, flat, problems, contrast_pairs)
    tw = emit_tailwind(semantic, components, flat, problems)

    # Ban-list guard at the token level: first-position banned fonts
    for k, v in flat.items():
        if "family" not in k:
            continue
        rv = resolve(v, flat, k, problems)
        first = str(rv).split(",")[0].strip().strip('"').replace(" ", "").lower()
        if first in {"inter", "roboto", "arial", "spacegrotesk", "space-grotesk"}:
            problems.append(f"{k}: banned font '{first}' in first position")

    for p in problems:
        print(f"FAIL: {p}")
    if problems:
        print(f"\n{len(problems)} token problem(s)")
        return 1

    if args.verify:
        # The CSS is what the floor reads and what the browser renders, so its
        # absence IS staleness. The Tailwind bridge is optional: a project that
        # does not use Tailwind never emits one, and demanding it would fail
        # every such project for a file it has no use for. Absent is reported,
        # never silently treated as fresh [A.6]; present is always compared.
        stale, notes = [], []
        checked = 0
        for path, want, required in ((args.out_css, css, True),
                                     (args.out_tailwind, tw, False)):
            try:
                with open(path, encoding="utf-8") as f:
                    have = f.read()
            except FileNotFoundError:
                if required:
                    stale.append(f"{path}: missing — the theme was never compiled")
                else:
                    notes.append(f"{path}: absent — no Tailwind bridge in this "
                                 f"project, nothing to go stale")
                continue
            checked += 1
            if have != want:
                stale.append(f"{path}: {first_difference(have, want)}")
        for n in notes:
            print(f"note: {n}")
        for s in stale:
            print(f"FAIL: {s}")
        if stale:
            print(f"\n{len(stale)} compiled file(s) no longer match {args.tokens} "
                  f"[D.41]. Re-run compile-tokens.py; never hand-edit the output.")
            return 1
        print(f"OK: {checked} compiled file(s) match {args.tokens} [D.41]")
        return 0

    if args.check_only:
        print(f"OK: tokens valid ({len(semantic)} semantic, {len(primitives)} primitive, "
              f"{len(components)} component, dark={'yes' if dark else 'no'})")
        return 0

    with open(args.out_css, "w", encoding="utf-8") as f:
        f.write(css)
    with open(args.out_tailwind, "w", encoding="utf-8") as f:
        f.write(tw)
    print(f"OK: wrote {args.out_css} and {args.out_tailwind} "
          f"({len(semantic)} semantic + {len(primitives)} primitive + "
          f"{len(components)} component tokens, "
          f"dark={'yes' if dark else 'no'})")
    return 0

if __name__ == "__main__":
    sys.exit(main())
