#!/usr/bin/env python3
"""build-showcase.py — auto-populate the Showcase from Verified Starters.

Every starter in starters/index.yaml becomes a gallery entry (metadata +
link to its skeleton + report). Harvested starters land in starters/ and
thus appear here automatically — the gallery never goes stale by design.

Usage: python3 showcase/build-showcase.py [--out showcase/index.html]
Exit: 0 written, 1 no starters, 2 usage/io.
"""
import datetime
import html
import os
import sys

try:
    import yaml
except ImportError:
    print("build-showcase: PyYAML required", file=sys.stderr)
    sys.exit(2)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CSS = """
body{font-family:system-ui,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#141312}
h1{font-size:1.6rem} .meta{color:#6e6a64;font-size:.85rem;margin-bottom:2rem}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem}
.card{border:1px solid #dddbd7;border-radius:8px;padding:1rem}
.card h2{font-size:1.05rem;margin:.2rem 0}
.badge{display:inline-block;font-size:.7rem;border:1px solid #dddbd7;border-radius:999px;
padding:.1rem .6rem;color:#6e6a64;margin-right:.3rem}
a{color:#0f6b3f;text-decoration:none} a:hover{text-decoration:underline}
.line{color:#4a4741;font-size:.9rem;margin:.5rem 0}
"""


def load_starters():
    path = os.path.join(ROOT, "starters", "index.yaml")
    with open(path, encoding="utf-8") as f:
        doc = yaml.safe_load(f)
    return doc if isinstance(doc, list) else (doc or {}).get("starters", [])


def render(starters):
    cards = []
    for s in starters:
        sid = html.escape(str(s.get("id", "?")))
        line = html.escape(str(s.get("line", "")))
        profile = html.escape(str(s.get("profile", "")))
        status = html.escape(str(s.get("status", "")))
        tags = " ".join(f'<span class="badge">{html.escape(str(t))}</span>'
                        for t in (s.get("tags") or [])[:4])
        cards.append(f"""<div class="card">
  <span class="badge">{profile}</span><span class="badge">{status}</span>
  <h2>{sid}</h2>
  <p class="line">{line}</p>
  <p>{tags}</p>
  <p><a href="../starters/{sid}/skeleton/index.html">skeleton</a> ·
     <a href="../starters/{sid}/report.md">report</a> ·
     <a href="../starters/{sid}/starter.yaml">manifest</a></p>
</div>""")
    today = datetime.date.today().isoformat()
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Design-Ops Showcase</title><style>{CSS}</style></head>
<body>
<h1>Design-Ops Showcase</h1>
<p class="meta">Auto-generated from starters/index.yaml on {today} —
{len(starters)} verified starter(s). Harvested projects appear here
automatically. Generated by showcase/build-showcase.py.</p>
<div class="grid">
{''.join(cards)}
</div>
</body></html>
"""


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    out = args[0] if args else os.path.join(ROOT, "showcase", "index.html")
    if "--out" in sys.argv:
        i = sys.argv.index("--out")
        out = sys.argv[i + 1]
    starters = load_starters()
    starters = [s for s in starters if isinstance(s, dict) and s.get("status") == "active"]
    if not starters:
        print("build-showcase: no active starters — nothing to show")
        return 1
    page = render(starters)
    with open(out, "w", encoding="utf-8") as f:
        f.write(page + "\n")
    print(f"OK: showcase with {len(starters)} entries -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
