#!/usr/bin/env python3
"""check-semantic-layer.py — D.39: an artefact must not step around a declared alias.

Design: Kimi, `Most/tasks/2026-08-06-kimi-s1-semantic-layer-spec.md`.

The defect this closes was found by П-4: the panel could offer no radius knob
on the reference landing, because the markup wrote `var(--radius-md)` — the
primitive — while the knob moves `semantic.radius.card`. An artefact that
steps around the declared layers makes every mechanism underneath it blind:
the panel, a restyle, any machine edit.

The rule is read from the skin, never from a list of banned names:

    a token whose $value is a single {reference} declares an alias —
    "prefer me over the thing I point at". The thing it points at is
    therefore a raw variable, and an artefact using it has an alternative.

That phrasing carries the honest-absence principle from П-4 in its shape: the
reference landing writes `var(--space-4)` 36 times and this check says nothing,
because no skin declares a spacing alias. Silence here is not an exemption, it
is the skin admitting the layer was never designed. Declare the alias and the
check starts guarding it with no change to this file.

Two boundaries are drawn by construction rather than by a list:

  * compiled themes are skipped by their generated-by marker, not by filename —
    primitives are legal in the emitter's own output;
  * component aliases do NOT make semantic variables raw. `button.primaryBg ->
    semantic.color.actionPrimary` says the button binds to that role, not that
    nobody else may use it; treating it as an alias would push every artefact
    into component tokens that exist for a handful of elements.

Usage: check-semantic-layer.py <root> --tokens <tokens.json> [--json] [--self-test]
Exit: 0 clean, 1 findings, 2 usage/io. Stdlib only.
"""
import argparse
import json
import os
import re
import sys
from importlib import import_module

HERE = os.path.dirname(os.path.abspath(__file__))
PKG_ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(PKG_ROOT, ".agents", "skills", "visual-director",
                                "scripts"))

try:
    _CT = import_module("compile-tokens")
except Exception:                                   # pragma: no cover
    _CT = None

SCAN_EXT = (".html", ".htm", ".css")
SKIP_DIRS = {".git", ".venv", "node_modules", "vendor", "__pycache__",
             "dist-vendor", ".next", ".cache"}
GENERATED_MARK = "GENERATED by compile-tokens.py"
VAR_USE = re.compile(r"var\(\s*(--[A-Za-z0-9_-]+)")
REF = re.compile(r"^\{(.+)\}$")


# --------------------------------------------------------------------------
# the map, built from declarations
# --------------------------------------------------------------------------
def alias_map(tokens_path):
    """{raw css var: [alias css vars, semantic first]}.

    Returns None when the skin cannot be read at all — a missing map is
    reported as such rather than silently passing everything [A.6]."""
    if _CT is None:
        return None
    try:
        with open(tokens_path, encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, ValueError):
        return None

    flat, problems = {}, []
    _CT.flatten(doc, [], flat, problems)

    out = {}
    for key, value in flat.items():
        if key.startswith("component."):
            continue                      # a binding, not a preference — see above
        if not isinstance(value, str):
            continue
        m = REF.match(value.strip())
        if not m:
            continue
        target = m.group(1)
        if target not in flat:
            continue                      # unresolved: compile-tokens' problem, not ours
        raw, alias = _CT.var_name(target), _CT.var_name(key)
        if raw == alias:
            continue                      # the dark layer aliasing its own name
        out.setdefault(raw, [])
        if alias not in out[raw]:
            out[raw].append((0 if key.startswith("semantic.") else 1, alias))

    # semantic first: it is the layer artefacts are meant to speak
    return {raw: [name for _rank, name in sorted(alts)]
            for raw, alts in out.items()}


# --------------------------------------------------------------------------
# the scan
# --------------------------------------------------------------------------
def is_generated(text):
    return GENERATED_MARK in text[:400]


def scan_files(root):
    for base, dirs, files in os.walk(root):
        dirs[:] = [d for d in sorted(dirs) if d not in SKIP_DIRS]
        for name in sorted(files):
            if name.lower().endswith(SCAN_EXT):
                yield os.path.join(base, name)


def findings(root, raws):
    out = []
    for path in scan_files(root):
        try:
            with open(path, encoding="utf-8", errors="replace") as f:
                text = f.read()
        except OSError:
            continue
        if is_generated(text):
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            for var in VAR_USE.findall(line):
                if var in raws:
                    out.append({"file": os.path.relpath(path, root),
                                "line": lineno, "raw": var,
                                "alternatives": raws[var]})
    return out


# --------------------------------------------------------------------------
def run(root, tokens_path, as_json=False):
    raws = alias_map(tokens_path)
    if raws is None:
        print("FAIL: could not read the alias map from %s — D.39 has nothing to "
              "check against, and passing without a map would be a false green"
              % tokens_path)
        return 1
    hits = findings(root, raws)

    if as_json:
        print(json.dumps({"aliased_tokens": len(raws),
                          "semantic_bypass_hits": len(hits),
                          "findings": hits}, ensure_ascii=False, indent=2))
        return 1 if hits else 0

    for h in hits:
        alts = " or ".join("`%s`" % a for a in h["alternatives"])
        print("FAIL: %s:%d uses %s — the skin declares %s for it"
              % (h["file"], h["line"], h["raw"], alts))
    if hits:
        print("\n%d semantic-layer bypass(es) [D.39]. Each one blinds the panel "
              "and every other machine edit: a knob moves the alias, not the "
              "primitive behind it. Replacing the name does not move a pixel — "
              "both resolve to the same value." % len(hits))
        return 1
    print("OK: no artefact steps around a declared alias (%d aliased token(s) "
          "guarded) [D.39]" % len(raws))
    return 0


# --------------------------------------------------------------------------
def self_test():
    import tempfile
    problems = []

    skin = {
        "primitive": {
            "color": {"gray": {"900": {"$value": "#141312", "$type": "color"}}},
            "radius": {"md": {"$value": "0.5rem", "$type": "dimension"}},
            "space": {"4": {"$value": "1rem", "$type": "dimension"}},
            "font": {
                "scale": {"step1": {"$value": "1.25rem", "$type": "dimension"}},
                "size": {"md": {"$value": "{primitive.font.scale.step1}",
                                "$type": "dimension"}},
            },
        },
        "semantic": {
            "color": {"ink": {"$value": "{primitive.color.gray.900}", "$type": "color"}},
            "radius": {"card": {"$value": "{primitive.radius.md}", "$type": "dimension"}},
        },
        "component": {
            "card": {"bg": {"$value": "{semantic.color.ink}", "$type": "color"}},
        },
    }

    with tempfile.TemporaryDirectory() as tmp:
        tokens = os.path.join(tmp, "tokens.json")
        with open(tokens, "w", encoding="utf-8") as f:
            json.dump(skin, f)

        # 1. both alias relations are built, and only where an alias exists
        raws = alias_map(tokens)
        if raws is None:
            return _fail(["alias map could not be built at all"])
        if raws.get("--radius-md") != ["--radius-card"]:
            problems.append("semantic->primitive alias missing: %r" % (raws.get("--radius-md"),))
        if raws.get("--font-scale-step1") != ["--font-size-md"]:
            problems.append("primitive->primitive alias missing: %r"
                            % (raws.get("--font-scale-step1"),))
        if "--space-4" in raws:
            problems.append("--space-4 was called raw with no alias declared for it")
        # 2b. a component binding must not make the semantic role raw
        if "--ink" in raws:
            problems.append("a component binding turned --ink into a raw variable")

        # 2. a finding carries the semantic alternative first
        art = os.path.join(tmp, "site")
        os.makedirs(art)
        with open(os.path.join(art, "index.html"), "w", encoding="utf-8") as f:
            f.write("<style>.c{border-radius:var(--radius-md);"
                    "padding:var(--space-4);font-size:var(--font-scale-step1)}</style>")
        hits = findings(art, raws)
        got = {h["raw"] for h in hits}
        if got != {"--radius-md", "--font-scale-step1"}:
            problems.append("wrong finding set: %r" % (sorted(got),))
        for h in hits:
            if h["raw"] == "--radius-md" and h["alternatives"][:1] != ["--radius-card"]:
                problems.append("semantic alternative was not offered first")

        # 3/4. the emitter's own output is not an artefact
        with open(os.path.join(art, "tokens.css"), "w", encoding="utf-8") as f:
            f.write("/* GENERATED by compile-tokens.py — do not edit by hand. */\n"
                    ":root{ --radius-card: var(--radius-md); }\n")
        if any(h["file"].endswith("tokens.css") for h in findings(art, raws)):
            problems.append("a compiled theme was audited as if it were an artefact")
        # ...and the exclusion is by marker, not by name
        with open(os.path.join(art, "tokens.css"), "w", encoding="utf-8") as f:
            f.write(":root{ --x: var(--radius-md); }\n")
        if not any(h["file"].endswith("tokens.css") for h in findings(art, raws)):
            problems.append("a hand-written file named tokens.css was skipped by "
                            "its name rather than by its generated marker")

    # 5. the flagship skins and the shipped starters are clean
    for skin_name in ("base-site", "base-app"):
        tokens = os.path.join(PKG_ROOT, "skins", skin_name, "tokens.json")
        if not os.path.isfile(tokens):
            problems.append("%s not found" % skin_name)
            continue
        raws = alias_map(tokens)
        if not raws:
            problems.append("%s declares no aliases at all" % skin_name)
            continue
        starters = os.path.join(PKG_ROOT, "starters")
        if os.path.isdir(starters) and skin_name == "base-site":
            hits = findings(starters, raws)
            if hits:
                problems.append("starters bypass the semantic layer in %d place(s): %s"
                                % (len(hits), ", ".join("%s:%d %s" % (h["file"], h["line"], h["raw"])
                                                        for h in hits[:3])))
    return _fail(problems)


def _fail(problems):
    for p in problems:
        print("FAIL: %s" % p)
    if problems:
        print("\n%d semantic-layer check problem(s)" % len(problems))
        return 1
    print("OK: check-semantic-layer self-test (alias map from declarations, "
          "semantic offered first, honest absence, generated output skipped by "
          "marker, starters clean) [D.39]")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--tokens", default=None)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()
    tokens = args.tokens
    if not tokens:
        for cand in ("artifacts/visual/tokens.json", "assets/tokens.json", "tokens.json"):
            p = os.path.join(args.root, cand)
            if os.path.isfile(p):
                tokens = p
                break
    if not tokens or not os.path.isfile(tokens):
        print("FAIL: no tokens.json to read the alias map from (pass --tokens)")
        return 1
    return run(args.root, tokens, args.json)


if __name__ == "__main__":
    sys.exit(main())
